build:
    environment:
        php: '7.4.19'

    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'

filter:
    excluded_paths: [tests/*]
